---
title: "EEB Office and Lab Networks"
author: "Lauren White" #" and Matt Michalska-Smith"
date: "4/27/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(message = FALSE)
```

## Load libraries and the anonymized EEB lab/office data

```{r}
library(magrittr)
library(tidygraph)
library(tidyverse)
library(igraph)
library(ggraph)

EEBdata<-read.csv("EEB-individ-data-cleaned.csv")
EEBdata$OfficeComb<- with(EEBdata, paste(O.bdg, Office))
EEBdata$LabComb<- with(EEBdata, paste(L.bdg, Lab))

mycols <- c("Susceptible" = "#2e294e", "Infectious" = "#d00000")
plot_graph <- function(g, title, outfile=NA) {
  p <- ggraph(g, layout=igraph::layout_nicely(g)) +
    geom_edge_link(edge_width=0.66, colour="#635E5B") +
    geom_node_point(aes(colour=status), size=3) +
    scale_colour_manual(values=mycols) +
    ggtitle(title) +
    theme_graph() +
    theme(legend.position="none")
  if (!is.na(outfile)) ggsave(p, filename=outfile, width=6, height=6)
  return(p)
}
```

## Office Layer

```{r}
office_el<-cbind(ID=EEBdata$UNIQUE, Office=EEBdata$OfficeComb)
office_el<-as.data.frame(office_el)
office_el<-distinct(office_el) #remove duplicate entries
office_el<-office_el[!(office_el$Office == " "),] #remove IDs with no office affiliation 

#Create bipartite network using sparse matrices
library('Matrix')
Office_bi <- spMatrix(nrow=length(unique(office_el$ID)),
        ncol=length(unique(office_el$Office)),
        i = as.numeric(factor(office_el$ID)),
        j = as.numeric(factor(office_el$Office)),
        x = rep(1, length(as.numeric(office_el$ID))) )
row.names(Office_bi) <- levels(factor(office_el$ID))
colnames(Office_bi) <- levels(factor(office_el$Office))

#Create a unipartite network where individuals have edges if they are assigned the same office room
Office_uni <- tcrossprod(Office_bi)

#plot the network
g<-graph_from_adjacency_matrix(Office_uni, mode = "undirected", weighted = NULL, diag = FALSE,  add.colnames = NULL, add.rownames = NA)
summary(g)
# plot(g, vertex.color="steelblue", vertex.label=NA, main="Office Network")
plot_graph(as_tbl_graph(g) %>% mutate(status = "Susceptible"), "Office Network", "figures/Office_Network.tiff")
```

```r

```

## Lab Layer
```{r}
lab_el<-EEBdata %>% select("ID"=UNIQUE, "Lab"=GROUP)
lab_el<-distinct(lab_el) #remove duplicate entries
lab_el<-lab_el[!(lab_el$Lab == " "),] #remove IDs with no office affiliation 

#Create bipartite network using sparse matrices
library('Matrix')
Lab_bi <- spMatrix(nrow=length(unique(lab_el$ID)),
        ncol=length(unique(lab_el$Lab)),
        i = as.numeric(factor(lab_el$ID)),
        j = as.numeric(factor(lab_el$Lab)),
        x = rep(1, length(as.numeric(lab_el$ID))) )
row.names(Lab_bi) <- levels(factor(lab_el$ID))
colnames(Lab_bi) <- levels(factor(lab_el$Lab))


#Create a unipartite network where individuals have edges if they are assigned the same office room
Lab_uni <- tcrossprod(Lab_bi)

#plot the network
h<-graph_from_adjacency_matrix(Lab_uni, mode = "undirected", weighted = NULL, diag = FALSE,  add.colnames = NULL, add.rownames = NA)
summary(h)
# plot(h, vertex.color="steelblue", vertex.label=NA, main="Lab Network")
plot_graph(as_tbl_graph(h) %>% mutate(status = "Susceptible"), "Lab Network", "figures/Lab_Network.tiff")
```

## Combine Layers
```{r}
g<-as_tbl_graph(g)
h<-as_tbl_graph(h)
full_graph<-graph_join(g, h, by="name") %>% to_undirected()

# plot(full_graph, vertex.color="steelblue", vertex.label=NA, main="Combined Office and Lab Network")
plot_graph(full_graph %>% mutate(status = "Susceptible"), "Combined Office and Lab Network", "figures/Full_Network.tiff")
```

